name: finwise
description: FinWise  is a comprehensive personal finance management app designed to empower users with effective tools for budgeting, expense tracking, and financial goal planning. Built using Flutter, Firebase, and following the BLoC pattern, FinWise provides a seamless and visually engaging experience for users to take control of their finances.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.1.6
  http: ^1.1.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_core: ^2.24.2
  equatable: ^2.0.5
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  generate: true
  assets:
    - assets/images/
    - assets/icons/


